import { Event } from "./types";

export const mockEvents: Event[] = [
  // {
  //   id: "saa-bootcamp",
  //   title: "AWS Certified Solutions Architect Associate Bootcamp",
  //   description:
  //     "A rigorous 3-day immersive camp designed to prepare builders for the SAA-C03 exam. Covers VPC design, advanced compute architecture, and cost optimization strategies.",
  //   category: "certification-camp",
  //   status: "upcoming",
  //   date: "Oct 24 - Oct 26",
  //   startDate: "2026-10-24",
  //   endDate: "2026-10-26",
  //   location: "Main Tech Hub",
  //   image:
  //     "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=2070&auto=format&fit=crop",
  //   isFeatured: true,
  //   isHighDemand: true,
  //   registrantsCount: 45,
  //   detailsLink: "#",
  // },
  // {
  //   id: "serverless-lambda",
  //   title: "Serverless Application Architecture with Lambda",
  //   description:
  //     "Learn to build scalable, event-driven applications using AWS Lambda, API Gateway, and DynamoDB. Zero server provisioning required.",
  //   category: "workshop",
  //   status: "upcoming",
  //   date: "Nov 05",
  //   startDate: "2026-11-05",
  //   endDate: "2026-11-05",
  //   location: "Virtual",
  //   image:
  //     "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
  //   isFeatured: false,
  //   isHighDemand: false,
  //   registrantsCount: 128,
  //   detailsLink: "#",
  // },
  // {
  //   id: "aws-innovation-challenge",
  //   title: "Build on AWS: 48-Hour Innovation Challenge",
  //   description:
  //     "Form a team, pitch an idea, and build a prototype utilizing AWS AI/ML services. Prizes for the most scalable and innovative solutions.",
  //   category: "hackathon",
  //   status: "upcoming",
  //   date: "Nov 12 - Nov 14",
  //   startDate: "2026-11-12",
  //   endDate: "2026-11-14",
  //   location: "Innovation Lab",
  //   image:
  //     "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
  //   isFeatured: false,
  //   isHighDemand: false,
  //   registrantsCount: 92,
  //   detailsLink: "https://www.meetup.com/awssbg-srmist/events/314368724/",
  // },
  {
    id: "eks-deep-dive",
    title: "Kubernetes & Containers on AWS: EKS Deep Dive",
    description:
      "Master containerized deployments on AWS. Learn ECS, EKS, Fargate, and how to build secure CI/CD pipelines for Kubernetes workloads.",
    category: "community-event",
    status: "upcoming",
    date: "Dec 02",
    startDate: "2026-12-02",
    endDate: "2026-12-02",
    location: "Tech Seminar Hall",
    image:
      "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 0,
    detailsLink: "https://www.meetup.com/awssbg-srmist/events/314368724",
  },
  {
    id: "kickstart-2",
    title: "AWS Kickstart - Edition 02",
    description:
      "Join the AWS Student Builders at SRMIST for our flagship online series focused on understanding core AWS cloud services from the ground up. This multi-part event is designed to give you a clear, practical introduction to how AWS works and how these services are used in real-world applications. Across the series, we will cover essential topics including compute (EC2), storage (S3), databases (RDS & DynamoDB), networking basics, and deployment strategies. Each session will include live explanations, demos, and use-case discussions to help you connect concepts with actual implementation. This event is suitable for beginners as well as students who want to strengthen their cloud fundamentals. By the end of the series, you will have a solid understanding of AWS services and how to start building on the cloud.",
    category: "speaker-session",
    status: "past",
    date: "May 09 09:30AM-11:00AM",
    startDate: "2026-05-09",
    endDate: "2026-05-09",
    location: "Virtual",
    image:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 25,
    detailsLink: "https://www.meetup.com/awssbg-srmist/events/314689778",
  },
  {
    id: "kickstart-1",
    title: "AWS Kickstart - Edition 01",
    description:
      "Join the AWS Student Builders at SRMIST for our flagship online series focused on understanding core AWS cloud services from the ground up. This multi-part event is designed to give you a clear, practical introduction to how AWS works and how these services are used in real-world applications. Across the series, we will cover essential topics including compute (EC2), storage (S3), databases (RDS & DynamoDB), networking basics, and deployment strategies. Each session will include live explanations, demos, and use-case discussions to help you connect concepts with actual implementation. This event is suitable for beginners as well as students who want to strengthen their cloud fundamentals. By the end of the series, you will have a solid understanding of AWS services and how to start building on the cloud.",
    category: "speaker-session",
    status: "past",
    date: "May 07 09:30AM-11.30AM",
    startDate: "2026-05-07",
    endDate: "2026-05-07",
    location: "Virtual",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 44,
    detailsLink: "https://www.meetup.com/awssbg-srmist/events/314648395",
  },
  {
    id: "aws-club-inaugration",
    title: "AWS Cloud Club - SRMIST Inaugration",
    description:
      "Join us for the official inauguration of AWS Cloud Club - SRMIST, a student-led community associated with AWS, focused on building real-world skills in cloud computing, DevOps, software development, and AI/ML. This event marks the beginning of a hands-on, project-driven journey where students go beyond theory to work on practical, scalable solutions using modern technologies within the AWS ecosystem.",
    category: "community-event",
    status: "past",
    date: "Apr 20 01:00PM - 03:00PM",
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    location: "Tech Park, SRMIST",
    image: "/events/aws-club-inaugration/image1.jpg",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 120,
    detailsLink: "https://www.meetup.com/awssbg-srmist/events/314368724",
  },
];
