import { Event } from "./types";

export const mockEvents: Event[] = [
  {
    id: "saa-bootcamp",
    title: "AWS Certified Solutions Architect Associate Bootcamp",
    description: "A rigorous 3-day immersive camp designed to prepare builders for the SAA-C03 exam. Covers VPC design, advanced compute architecture, and cost optimization strategies.",
    category: "certification-camp",
    status: "upcoming",
    date: "Oct 24 - Oct 26",
    startDate: "2026-10-24",
    endDate: "2026-10-26",
    location: "Main Tech Hub",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=2070&auto=format&fit=crop",
    isFeatured: true,
    isHighDemand: true,
    registrantsCount: 45,
    detailsLink: "#"
  },
  {
    id: "serverless-lambda",
    title: "Serverless Application Architecture with Lambda",
    description: "Learn to build scalable, event-driven applications using AWS Lambda, API Gateway, and DynamoDB. Zero server provisioning required.",
    category: "workshop",
    status: "upcoming",
    date: "Nov 05",
    startDate: "2026-11-05",
    endDate: "2026-11-05",
    location: "Virtual",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 128,
    detailsLink: "#"
  },
  {
    id: "aws-innovation-challenge",
    title: "Build on AWS: 48-Hour Innovation Challenge",
    description: "Form a team, pitch an idea, and build a prototype utilizing AWS AI/ML services. Prizes for the most scalable and innovative solutions.",
    category: "hackathon",
    status: "upcoming",
    date: "Nov 12 - Nov 14",
    startDate: "2026-11-12",
    endDate: "2026-11-14",
    location: "Innovation Lab",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: true,
    registrantsCount: 92,
    detailsLink: "#"
  },
  {
    id: "eks-deep-dive",
    title: "Kubernetes & Containers on AWS: EKS Deep Dive",
    description: "Master containerized deployments on AWS. Learn ECS, EKS, Fargate, and how to build secure CI/CD pipelines for Kubernetes workloads.",
    category: "workshop",
    status: "upcoming",
    date: "Dec 02",
    startDate: "2026-12-02",
    endDate: "2026-12-02",
    location: "Tech Seminar Hall",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 56,
    detailsLink: "#"
  },
  {
    id: "clf-bootcamp-past",
    title: "AWS Cloud Practitioner Essentials Bootcamp",
    description: "Structured 2-day study group and prep course covering cloud concepts, security, architecture, billing, and pricing. Vouchers were distributed to attendees.",
    category: "certification-camp",
    status: "past",
    date: "Sep 14 - Sep 15",
    startDate: "2026-09-14",
    endDate: "2026-09-15",
    location: "Main Tech Hub",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 120,
    detailsLink: "#"
  },
  {
    id: "cloud-fundamentals-past",
    title: "Introduction to AWS & Cloud Fundamentals",
    description: "A hands-on virtual intro workshop. Participants set up their first AWS Free Tier accounts, launched EC2 instances, and hosted static sites on S3.",
    category: "workshop",
    status: "past",
    date: "Aug 20",
    startDate: "2026-08-20",
    endDate: "2026-08-20",
    location: "Virtual",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 210,
    detailsLink: "#"
  },
  {
    id: "cloud-clash-past",
    title: "Cloud Clash 2025: Serverless Showdown",
    description: "Our annual hackathon focused on serverless technology. 30 teams built highly responsive and scalable apps using AWS Amplify, Lambda, and DynamoDB.",
    category: "hackathon",
    status: "past",
    date: "Mar 10 - Mar 12",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    location: "Innovation Lab",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=2070&auto=format&fit=crop",
    isFeatured: false,
    isHighDemand: false,
    registrantsCount: 140,
    detailsLink: "#"
  }
];
